// LOGIC FILE NÀY ĐÃ ĐƯỢC CHUYỂN SANG:
// - 02_Config.js (Cấu hình)
// - 03_LoggerService.js (Logger)
// - 04_CRUD_Service.js (Dropdown Lists & Rules)
// - 04.1_Sidebar.html (Sidebar Dropdown Manager)
// - 05_SheetManager_Service.js (Sheet Manager)
// - 05.1_SheetManager.html (Sidebar Sheet Manager UI)
// - 06_TemplateManagerService.js (Template Manager)
// - 06.1_TemplateManager.html (Sidebar Template Manager UI)
// - 07_SystemMenu.js (System Menu Modal)
// - 07.1_SystemMenu.html (System Menu Modal UI)
// - 08_Main.js (Cổng kết nối API chính)
// - 09_Test.js (Bộ kiểm thử tự động)
// - 10_DestinationCode.js (Mã nguồn tham khảo cho file đích)
// - 11_DataEntry.js (Nhập liệu backend)
// - 11.1_DataEntry.html (Sidebar Nhập liệu UI)
